version: '3.8'
services:
  mongodb:
    container_name: lunchbot-database
    image: mongo
    ports:
      - '27017:27017'
  backend:
    container_name: lunchbot-backend
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - mongodb
    ports:
      - '4001:4001'
    volumes:
      - './src:/app/src'
      - './node_modules:/app/node_modules'
    environment:
      DATABASE_HOST: mongodb
      NODE_ENV: development
      PORT: 4001
