version: '3.8'
services:
  mongodb:
    container_name: lunchbot-database
    image: mongo
    restart: always
    env_file:
      - ./env/database.env
    volumes:
      - lunchbot_production:/data/db
    ports:
      - '27017:27017'
  backend:
    image: systek.socialbot:latest
    container_name: lunchbot-backend
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    depends_on:
      - mongodb
    ports:
      - '80:80'
    restart: always
    env_file:
      - ./env/common.prod.env
      - ./env/secrets.env
volumes:
  lunchbot_production:
    external: false
