version: '3.8'
services:
  mongodb:
    container_name: lunchbot-database
    image: mongo
  backend:
    container_name: lunchbot-backend
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    depends_on:
      - mongodb
    ports:
      - '80:80'
    env_file:
      - ./env/common.dev.env
