version: '3.8'
services:
  backend:
    image: systek.socialbot:latest
    container_name: lunchbot-backend
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - '80:80'
    restart: always
    env_file:
      - ./env/common.prod.env
