name: Deploy Node.js project to function app

on:
  - push
  - workflow_dispatch

env:
  AZURE_FUNCTIONAPP_NAME: systek-social-bot # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: false

      - name: 'Log in to docker registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: 'Compose Customized Docker Image'
        shell: bash
        run: |
          docker build -f ./docker/Dockerfile.prod . -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/systeksocial/slackbot:${{ github.sha }}
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/systeksocial/slackbot:${{ github.sha }}

      - name: 'Run Azure Functions Container Action'
        uses: Azure/functions-container-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/systeksocial/slackbot:${{ github.sha }}
